services:
    nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/app:ro,cached
      networks:
        - app-network
      depends_on:
        - php

    php:
      build:
        context: .
        dockerfile: docker/Dockerfile
      restart: unless-stopped
      volumes:
        - .:/var/app:rw
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/dev.ini
      networks:
        - app-network
      depends_on:
        - postgres

    postgres:
      image: postgres:14.15-alpine3.21
      ports:
        - "5432:5432"
      restart: always
      environment:
        - POSTGRES_PASSWORD=password
      volumes:
        - ./var/postgresql/data:/var/lib/postgresql/data
        - ./var/postgresql/logs:/var/log/postgresql:cached
      networks:
        - app-network

    rabbitmq:
      image: rabbitmq:4-management-alpine
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ./var/rabbitmq/data:/var/lib/rabbitmq
        - ./var/rabbitmq/logs:/var/log/rabbitmq
      networks:
        - app-network

    redis:
      image: redis:7.4-alpine
      ports:
        - "6379:6379"
      networks:
        - app-network

networks:
    app-network:
      driver: bridge